/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

export { WebVitalsInstrumentation } from './instrumentation.ts';
export {
  ATTR_WEB_VITAL_ATTRIBUTION_CACHE_DURATION,
  ATTR_WEB_VITAL_ATTRIBUTION_CONNECTION_DURATION,
  ATTR_WEB_VITAL_ATTRIBUTION_DNS_DURATION,
  ATTR_WEB_VITAL_ATTRIBUTION_ELEMENT_RENDER_DELAY,
  ATTR_WEB_VITAL_ATTRIBUTION_FIRST_BYTE_TO_FCP,
  ATTR_WEB_VITAL_ATTRIBUTION_INPUT_DELAY,
  ATTR_WEB_VITAL_ATTRIBUTION_INTERACTION_TARGET,
  ATTR_WEB_VITAL_ATTRIBUTION_INTERACTION_TYPE,
  ATTR_WEB_VITAL_ATTRIBUTION_LARGEST_SHIFT_TARGET,
  ATTR_WEB_VITAL_ATTRIBUTION_LARGEST_SHIFT_VALUE,
  ATTR_WEB_VITAL_ATTRIBUTION_LOAD_STATE,
  ATTR_WEB_VITAL_ATTRIBUTION_NEXT_PAINT_TIME,
  ATTR_WEB_VITAL_ATTRIBUTION_PRESENTATION_DELAY,
  ATTR_WEB_VITAL_ATTRIBUTION_PROCESSING_DURATION,
  ATTR_WEB_VITAL_ATTRIBUTION_REQUEST_DURATION,
  ATTR_WEB_VITAL_ATTRIBUTION_RESOURCE_LOAD_DELAY,
  ATTR_WEB_VITAL_ATTRIBUTION_RESOURCE_LOAD_DURATION,
  ATTR_WEB_VITAL_ATTRIBUTION_TARGET,
  ATTR_WEB_VITAL_ATTRIBUTION_TIME_TO_FIRST_BYTE,
  ATTR_WEB_VITAL_ATTRIBUTION_URL,
  ATTR_WEB_VITAL_ATTRIBUTION_WAITING_DURATION,
  ATTR_WEB_VITAL_DELTA,
  ATTR_WEB_VITAL_ID,
  ATTR_WEB_VITAL_NAME,
  ATTR_WEB_VITAL_NAVIGATION_TYPE,
  ATTR_WEB_VITAL_RATING,
  ATTR_WEB_VITAL_VALUE,
  WEB_VITAL_EVENT_NAME,
} from './semconv.ts';
export type { WebVitalsInstrumentationConfig } from './types.ts';
